mindmap
root(DevOps roadmap))
  (Enablement)
    ::icon(fa-brands fa-github)
        GitHub: Source code, CI/CD and AI Copilot
        Terraform: Infrastructure as Code
        ArgoCD: Infrastructure deployment management
        Gradle: Build, release automation
        Harbor: Artifact push-proxy
        Nexus: Artifact repository
        Container Registry: docker images repo
  (Observability)
        Grafana: Dashboards, Alerts, Events, Adhoc investigations
        VictoriaMetrics: Service, infrastructure metrics
        OpsGenie + Slack: Routing alerts based on criticality
        Elastic Stack: Log persistence + exploration
