mindmap
root(DevOps roadmap))
  (Developer tooling)
    ::icon(fa-brands fa-github)
        GitHub: Code & CI/CD
        Terraform: Infrastructure as code
        Gradle: Builds, release automation
        Harbor: Artifact push-proxy
        Nexus: General artifact repository
        Container Registry: built docker images
  (Observability)
        Grafana: Dashboards, Alerts, Adhoc investigations
        VictoriaMetrics: Service \and infrastructure metrics
        Elastic Stack: Log persistent \and retrieval
