mindmap
root(Tech Radar)
  Data and Machine Learning
  ::icon(fa-solid fa-chart-pie)
    BigQuery: Data Warehouse
    AI Platform: ML models
    Dataflow: Stream / Batch processing
    Dataproc: Big Data
  Storage Solutions
  ::icon(fa-solid fa-database)
    Cloud Storage: Object storage
    Filestore: Filesystems
    Cloud SQL: SQL databases
    AlloyDB: PostgreSQL databases
    MongoDB Atlas: NoSQL databases
    Firestore: NoSQL database
  Compute and GKE
    ::icon(fa-solid fa-microchip)
    GKE: Kubernetes clusters
    GKE Autopilot: Managed kubernetes
    Compute Engine: VMs
    Cloud Functions: Serverless/functions
    Cloud Run: Kubernetes containers
  Build and Deployment
  ::icon(fa-brands fa-github)
    Cloud Build: CI/CD
    Artifact Registry: Software artifacts
    Container Registry: Docker images
    GitHub: Source Code
    GitHub Actions: CI/CD
    Jenkins: CI/CD
    Gradle: Build/releases
    Harbor: Docker proxy
    Nexus Repository OSS: Software artifacts

