mindmap
root(RG Cloud Radar))
  (Data platform)
  ::icon(fa-solid fa-chart-pie)
                BigQuery: Data Warehouse
                AI Platform: ML + AI
                Dataflow: Stream & Batch
                Dataproc: Big Data
                Composer: Scheduling
  (Compute + Web platform)
    ::icon(fa-solid fa-microchip)
                GKE: K8s clusters
                Autopilot GKE*: Run pods
                Compute Engine: Run VMs 
                Cloud Functions*: Serverless
                Cloud Run*: Containers
                Consul/Envoy: Service Mesh
                Cloudflare: Site delivery, workers,security
  (Storage)
        ::icon(fa-solid fa-database)
                Cloud Storage: Object store
                Cloud SQL: SQL DBs
                MongoDB Atlas: NoSQL DB   
