mindmap
root((Cloud Tech Radar))
  (Data and ML)
  ::icon(fa-solid fa-chart-pie)
      BigQuery: Data Warehouse
      AI Platform: ML models
      Dataflow: Stream / Batch processing
      Dataproc: Big Data
      Cloud composer: orchestration
  (Storage Solutions)
  ::icon(fa-solid fa-database)
        Cloud Storage: Object storage
        Cloud SQL: SQL DB
        AlloyDB: PostgreSQL DB
        MongoDB Atlas: NoSQL DB
  (Compute and GKE)
    ::icon(fa-solid fa-microchip)
      GKE: Flexible Kubernetes
      Autopilot GKE: Managed cluster
      Compute Engine: VM instances
      Cloud Functions: Serverless
      Cloud Run: Multi/containers
      Consul Connect: Service Mesh
  (DevOps Tooling)
    ::icon(fa-brands fa-github)
      Cloud Build: CI/CD
      Artifact Registry: Build artifacts
      Container Registry: Docker images
      GitHub: Source Code
      GitHub Actions: CI/CD
      Jenkins: CI/CD
      Gradle: Software builds
      Harbor: Docker image proxy
      Nexus: Build artifacts

